---
- name: Setup HAProxy
  hosts: nginx
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:
  - name: set hostname
    hostname:
      name: "{{ new_hostname }}"
  - name: Run apg-get update & apt-get install nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes
  - name: Create nginx configuration
    copy: 
      src: files/nginx.conf
      dest: /etc/nginx/nginx.conf
      mode: 0644
    notify:
      - Restart nginx
  - name: Start nginx
    ansible.builtin.systemd:
      name: nginx
      state: started
      enabled: yes
  handlers:
  - name: Restart nginx
    service:
      name: nginx
      state: restarted