---
- name: Rename hosts
  hosts: worker
  vars:
    token: "{{ lookup('file','files/node-token') }}"
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks: 
  - name: set hostnames
    hostname:
      name: "{{ new_hostname }}"
  - name: Install K3s worker
    shell: curl -sfL https://get.k3s.io | K3S_URL=https://{{ nginx_ip}}:6443 K3S_TOKEN={{ token }} sh -   