---
- name: Setup mysql
  no_log: no
  hosts: mysql
  become: yes
  become_method: sudo
  gather_facts: yes
  tags: [mysql]
  tasks:
  - name: set hostname
    hostname:
      name: "{{ new_hostname }}"
  # - name: include vars
  #   include_vars:
  #     dir: group_vars
  - name: install ansible python3 mysql dependency
    apt:
      name: python3-mysqldb
      state: latest
      update_cache: yes
  - name: install mysql-server
    apt:
      name: mysql-server
      state: latest
  - name: Enable remote login to mysql
    lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^bind-address'
      line: 'bind-address = 0.0.0.0'
      backup: yes
    notify:
      - Restart mysql
  - name: copy my.cnf 
    copy:
      src: files/my.cnf
      dest: /etc/my.cnf
      mode: 0644
  - name: Start mysql
    ansible.builtin.systemd:
      name: mysql
      state: started
      enabled: yes 

  - name: Create K3s database
    community.mysql.mysql_db:
      name: "{{ k3s_database_name }}"
      state: present
      collation: latin1_swedish_ci
  - name: Create remote users
    community.mysql.mysql_user:
      name: "{{ k3s_username }}"
      password: "{{ k3s_db_passwd }}"
      host: '%'
      priv: '*.*:ALL'
      state: present

  handlers:
  - name: Restart mysql
    service:
      name: mysql
      state: restarted